version: '2'
services:
  nh1:
    image: dpaneda/nethealth
    environment:
        - ENDPOINTS=nh2,nh3
  nh2:
    image: dpaneda/nethealth
    environment:
        - ENDPOINTS=nh1,nh3
  nh3:
    image: dpaneda/nethealth
    environment:
        - ENDPOINTS=nh1,nh2
  statsd:
    image: hopsoft/graphite-statsd
    ports:
      - "80:80"
